// <auto-generated />
using System;
using CompanyCommunicator.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompanyCommunicator.Core.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260219010712_AddInstallLookupIndexAndTeamAadGroupId")]
    partial class AddInstallLookupIndexAndTeamAadGroupId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompanyCommunicator.Core.Data.Entities.AppConfiguration", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("AppConfiguration", (string)null);
                });

            modelBuilder.Entity("CompanyCommunicator.Core.Data.Entities.ExportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequestedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.ToTable("ExportJobs", (string)null);
                });

            modelBuilder.Entity("CompanyCommunicator.Core.Data.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<bool>("AllUsers")
                        .HasColumnType("bit");

                    b.Property<string>("Author")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ButtonLink")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ButtonTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CanceledCount")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ImageBlobName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImageLink")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("RecipientNotFoundCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SucceededCount")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TotalRecipientCount")
                        .HasColumnType("int");

                    b.Property<string>("TrackingUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("UnknownCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Notifications", null, t =>
                        {
                            t.HasCheckConstraint("CK_Notifications_Status", "[Status] IN ('Draft','Scheduled','Queued','SyncingRecipients','InstallingApp','Sending','Sent','Canceled','Failed')");
                        });
                });

            modelBuilder.Entity("CompanyCommunicator.Core.Data.Entities.NotificationAudience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AudienceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AudienceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId")
                        .HasDatabaseName("IX_NotificationAudiences_NotificationId");

                    b.ToTable("NotificationAudiences", null, t =>
                        {
                            t.HasCheckConstraint("CK_NotificationAudiences_AudienceType", "[AudienceType] IN ('Team','Roster','Group')");
                        });
                });

            modelBuilder.Entity("CompanyCommunicator.Core.Data.Entities.SentNotification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ConversationId")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RecipientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RecipientType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ServiceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId", "DeliveryStatus")
                        .HasDatabaseName("IX_SentNotifications_NotificationId_DeliveryStatus");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("NotificationId", "DeliveryStatus"), new[] { "SentDate", "StatusCode" });

                    b.HasIndex("NotificationId", "Id")
                        .HasDatabaseName("IX_SentNotifications_Install_Lookup_User")
                        .HasFilter("[ConversationId] IS NULL AND [DeliveryStatus] = 'Queued' AND [RecipientType] = 'User'");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("NotificationId", "Id"), new[] { "RecipientId", "ServiceUrl" });

                    b.HasIndex("NotificationId", "RecipientId")
                        .IsUnique()
                        .HasDatabaseName("UX_SentNotifications_NotificationId_RecipientId");

                    b.ToTable("SentNotifications", null, t =>
                        {
                            t.HasCheckConstraint("CK_SentNotifications_DeliveryStatus", "[DeliveryStatus] IN ('Queued','Succeeded','Failed','RecipientNotFound','Retrying')");
                        });
                });

            modelBuilder.Entity("CompanyCommunicator.Core.Data.Entities.Team", b =>
                {
                    b.Property<string>("TeamId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AadGroupId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("InstalledDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ServiceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TeamId");

                    b.HasIndex("AadGroupId")
                        .IsUnique()
                        .HasDatabaseName("IX_Teams_AadGroupId")
                        .HasFilter("[AadGroupId] IS NOT NULL");

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("CompanyCommunicator.Core.Data.Entities.ThrottleState", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ConcurrentSends")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RetryAfterUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("ThrottleState", (string)null);
                });

            modelBuilder.Entity("CompanyCommunicator.Core.Data.Entities.User", b =>
                {
                    b.Property<string>("AadId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConversationId")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("HasTeamsLicense")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSyncedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LicenseCheckedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ServiceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Upn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AadId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CompanyCommunicator.Core.Data.Entities.ExportJob", b =>
                {
                    b.HasOne("CompanyCommunicator.Core.Data.Entities.Notification", "Notification")
                        .WithMany("ExportJobs")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("CompanyCommunicator.Core.Data.Entities.NotificationAudience", b =>
                {
                    b.HasOne("CompanyCommunicator.Core.Data.Entities.Notification", "Notification")
                        .WithMany("Audiences")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("CompanyCommunicator.Core.Data.Entities.SentNotification", b =>
                {
                    b.HasOne("CompanyCommunicator.Core.Data.Entities.Notification", "Notification")
                        .WithMany("SentNotifications")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("CompanyCommunicator.Core.Data.Entities.Notification", b =>
                {
                    b.Navigation("Audiences");

                    b.Navigation("ExportJobs");

                    b.Navigation("SentNotifications");
                });
#pragma warning restore 612, 618
        }
    }
}
